AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::DataSync::LocationEFS resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.datasync.locationefs.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-datasync-locationefs-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.datasync.locationefs.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-datasync-locationefs-handler-1.0-SNAPSHOT.jar
